### ISSUE TITLE
Data model design

### ISSUE THREAD

**Issue by Kosudo** [Kosudo/nextSIS#2]
Produce a data model (diagram) for nextSIS.

**Comment by Kosudo** [comment]
I'm having a rethink about this. Originally intended to pragmatically define entities essentially on the basis of roles - student, teacher, etc. - but am now coming around to the idea of generically defining people as an entity. It probably doesn't have profound end-user implications but it does have more significantly more impact on the design. Want to get this right as it's not easy to go back from here.

**Comment by lkozloff** [comment]
I think it makes sense to having a generic 'person' entity - but how do you foresee it working in terms of defining the relationships between people and permissions? That hammered down, I think it's more extensible and will allow for your parent/teacher combos (or our administrator/teacher combos).

**Comment by Kosudo** [comment]
It's tempting to see this as logically leading to role as a job which is an entity within the entity-relationship diagram, and seeing the job as having permissions as attributes, but in reality it's better to support the flexibility of inheriting a role into which individual permissions can be allowed in an extensible modular system, so a person has permissions as a separate table. The data model has to be able to support combinations of roles definitely.
