### ISSUE TITLE
config.php and database.php templates

### ISSUE THREAD

**Issue by lkozloff** [Kosudo/nextSIS#7]
Looks like the .gitignore file lists application/config/config.php and database.php 

Makes sense, but can we put up template files that give some clue to what they should look like?

**Comment by Kosudo** [comment]
config.php and database.php are standard CodeIgniter files with locally-dependent parameter changes but for simplicity I've uploaded config.template.php and database.template.php which need to be renamed as config.php and database.php - these files are quite CI-comment heavy so I've capitalised my comments by the lines that need changing for emphasis.

In config.template.php these are line 17 (your development server), line 72 (language), 227 (encryption key for sessions).

In database.template.php these are lines 51 - 53 - your database hostname, username and password.
